id: medcom.sor.mcsd
canonical: http://medcomfhir.dk/ig/medcom-sor
version: 0.0.1-current
name: MedCom_SOR_mCSD
title: "MedCom version of Mobile Care Services Discovery (mCSD)"
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2023-05-01
status: active
publisher:
  - name: Medcom (IHE IT Infrastructure Technical Committee)
  - url: https://www.ehmi.dk/
  - email: ovi@medcom.dk
contact:
  - name: MedCom (IHE IT Infrastructure Technical Committee)
    telecom:
      - system: email
        value: ovi@medcom.dk
description: MedCom embrace of The IHE Mobile Care Services Discovery (mCSD) IG provides a transaction for mobile and lightweight browser-based applications to find and update care services resources.
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+
dependencies:
  ihe.iti.balp: current # 1.1.1



parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  special-url: 
    - urn:ihe:event-type-code


pages:
  index.md:
    title: Mobile Care Services Discovery (mCSD)
    generation: markdown
  volume-1.md:
    title: 1:46 Mobile Care Services Discovery (mCSD)
    generation: markdown
  ITI-90.md:
    title: 2:3.90 Find Matching Care Services [ITI-90]
    generation: markdown
  ITI-91.md:
    title: 2:3.91 Request Care Services Updates [ITI-91]
    generation: markdown
  testplan.md:
    title: mCSD Test Plan
    generation: markdown
  issues.md:
    title: mCSD Open and Closed issues
    generation: markdown
  other.md:
    title: Changes to Other Documents
    generation: markdown


menu:
  MedCom mCSD Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors, Transactions, and Content Modules: volume-1.html#1461-mcsd-actors-transactions-and-content-modules
    Actor Options: volume-1.html#1462-mcsd-actor-options
    Required Groupings: volume-1.html#1463-mcsd-required-actor-groupings
    Overview: volume-1.html#1464-mcsd-overview
    Security Considerations: volume-1.html#1465-mcsd-security-considerations
    Cross-Profile Considerations: volume-1.html#1466-mcsd-cross-profile-considerations
    Deployment Considerations: volume-1.html#1467-mcsd-deployment-considerations  
    Endpoint Usage Considerations: volume-1.html#1468-mcsd-endpoint-usage-considerations
  Volume 2:
    "Find Matching Care Services [ITI-90]": ITI-90.html
    "Request Care Services Updates [ITI-91]": ITI-91.html 
  Test Plan: testplan.html
  Artifacts: artifacts.html
#  Profiles: profiles.html
  Other: other.html
